In [1]:
import os,math,warnings,math,pickle,random

from mpl_toolkits.mplot3d.proj3d import transform
from numpy.array_api import trunc

warnings.filterwarnings('ignore')
from collections import defaultdict

import pandas as pd
import numpy as np
from tqdm import tqdm

# 用于向量检索的库
import faiss

from sklearn.preprocessing import MinMaxScaler,LabelEncoder
from tensorflow.keras import backend as K
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.sequence import pad_sequences
import tensorflow.keras as keras

C:\Users\ROG\AppData\Local\Temp\ipykernel_38872\742385918.py:3: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  from numpy.array_api import trunc

# 1.读取数据

In [2]:
def get_all_click_sample(sample_nums=10000):
    '''debug模式，从训练集中抽取一部分数据调试代码'''
    all_click=pd.read_csv('./data/train_click_log.csv')
    all_user_ids=all_click.user_id.unique()
    sample_user_ids=np.random.choice(all_user_ids,size=sample_nums,replace=False)
    all_click=all_click[all_click['user_id'].isin(sample_user_ids)]
    all_click=all_click.drop_duplicates(['user_id','click_article_id','click_timestamp'])
    return all_click

def get_all_click_df(offline):
    '''读取点击数据，分为线上和线下，线下用训练集数据，线上用训练集+测试集'''
    if offline:
        all_click=pd.read_csv('./data/train_click_log.csv')
    else:
        trn_click=pd.read_csv('./data/train_click_log.csv')
        tst_click=pd.read_csv('./data/testA_click_log.csv')
        all_click=pd.concat([trn_click,tst_click]).reset_index(drop=True)
    all_click=all_click.drop_duplicates(['user_id','click_article_id','click_timestamp'])
    return all_click

In [3]:
def get_item_info_df():
    '''读取文章的基本属性'''
    item_info_df=pd.read_csv('./data/articles.csv')
    item_info_df=item_info_df.rename(columns={'article_id':'click_article_id'})
    return item_info_df

In [4]:
def get_item_emb_dict():
    '''读取文章的embedding'''
    item_emb_df=pd.read_csv('./data/articles_emb.csv')
    item_emb_cols=[x for x in item_emb_df.columns if 'emb' in x]
    # 把embedding转换成numpy数组，ascontiguousarray确保在内存中连续
    item_emb_np=np.ascontiguousarray(item_emb_df[item_emb_cols])
    # L2归一化
    item_emb_np=item_emb_np/np.linalg.norm(item_emb_np,axis=1,keepdims=True)
    item_emb_dict=dict(zip(item_emb_df['article_id'],item_emb_np))
    pickle.dump(item_emb_dict,open('./save/item_content_emb.pkl','wb'))
    return item_emb_dict

In [5]:
all_click_df=get_all_click_sample()
# 对时间戳归一化，按照all_click_df[['click_timestamp']]取出的是DataFrame，使用apply会对列进行操作，而all_click_df['click_timestamp']是对每个元素单独操作，取最值只会取到自己
all_click_df['click_timestamp']=all_click_df[['click_timestamp']].apply(lambda x:(x-np.min(x))/(np.max(x)-np.min(x)))

In [6]:
all_click_df.head()

,user_id,click_article_id,click_timestamp,click_environment,click_deviceGroup,click_os,click_country,click_region,click_referrer_type
11,199995,336476,0.000127,4,1,17,1,25,2
12,199995,283933,0.000195,4,1,17,1,25,1
13,199995,353667,0.000210,4,1,17,1,25,1
123,199961,64329,0.000353,4,1,17,1,20,5
124,199961,199198,0.000408,4,1,17,1,20,1

In [7]:
item_info_df=get_item_info_df()

In [8]:
item_emb_dict=get_item_emb_dict()

# 2.工具函数

In [9]:
def get_user_item_time(click_df):
    '''获取用户-文章-点击时间字典 {user1:{item1:time1,item2:time2}}'''
    memo={}
    for user_id,group in click_df.groupby('user_id'):
        group_sorted=group.sort_values('click_timestamp')
        item_time_dict=dict(zip(group_sorted['click_article_id'],group_sorted['click_timestamp']))
        memo[user_id]=item_time_dict
    return memo

In [10]:
def get_item_user_time(click_df):
    '''获取文章-用户-点击时间字典  {item1: {user1: time1, user2: time2...}...}'''
    memo={}
    for click_article_id,group in click_df.groupby('click_article_id'):
        group_sorted=group.sort_values('click_timestamp')
        item_time_dict=dict(zip(group_sorted['user_id'],group_sorted['click_timestamp']))
        memo[click_article_id]=item_time_dict
    return memo

In [11]:
def get_hist_and_last_click(all_click):
    '''获取当前数据的历史点击（不包括最后一次）和最后一次点击'''
    all_click = all_click.sort_values(by=['user_id', 'click_timestamp'])
    click_last_df = all_click.groupby('user_id').tail(1)

    # 如果用户只有一个点击，hist为空了，会导致训练的时候这个用户不可见，此时默认泄露一下
    def hist_func(user_df):
        if len(user_df) == 1:
            return user_df
        else:
            return user_df[:-1]

    click_hist_df = all_click.groupby('user_id').apply(hist_func).reset_index(drop=True)

    return click_hist_df, click_last_df

In [12]:
def get_item_info_dict(item_info_df):
    '''获取文章id对应的各个属性'''
    max_min_scaler=lambda x:(x-np.min(x))/(np.max(x)-np.min(x))
    item_info_df['created_at_ts']= item_info_df[['created_at_ts']].apply(max_min_scaler)
    item_type_dict=dict(zip(item_info_df['click_article_id'],item_info_df['category_id']))
    item_words_dict=dict(zip(item_info_df['click_article_id'],item_info_df['words_count']))
    item_created_time_dict=dict(zip(item_info_df['click_article_id'],item_info_df['created_at_ts']))
    return item_type_dict,item_words_dict,item_created_time_dict

In [13]:
def get_item_topk_click(click_df,k):
    '''获取点击次数最多的k个物品'''
    return click_df['click_article_id'].value_counts().index[:k]

In [14]:
def get_user_hist_item_info_dict(all_click):
    '''获取用户历史点击的文章信息'''

    # 获取用户user_id对应的历史点击文章类型的集合字典
    user_hist_item_types=all_click.groupby('user_id')['category_id'].agg(set).reset_index()
    user_hist_item_types_dict=dict(zip(user_hist_item_types['user_id'],user_hist_item_types['category_id']))
    # 获取user_id对应的用户点击文章的集合
    user_hist_item_ids_dict=all_click.groupby('user_id')['click_article_id'].agg(set).reset_index()
    user_hist_item_ids_dict=dict(zip(user_hist_item_ids_dict['user_id'],user_hist_item_ids_dict['click_article_id']))

    # 获取user_id对应的用户历史点击的文章的平均字数字典
    user_hist_item_words=all_click.groupby('user_id')['words_count'].agg("mean").reset_index()
    user_hist_item_words_dict=dict(zip(user_hist_item_words['user_id'],user_hist_item_words['words_count']))

    # 获取user_id对应的用户最后一次点击的文章的创建时间
    all_click_=all_click.sort_values('click_timestamp')
    user_last_item_created_time=all_click_.groupby('user_id')['created_at_ts'].apply(lambda x:x.iloc[-1]).reset_index()
    max_min_scaler = lambda x : (x-np.min(x))/(np.max(x)-np.min(x))
    user_last_item_created_time['created_at_ts']=user_last_item_created_time[['created_at_ts']].apply(max_min_scaler)
    user_last_item_created_time_dict=dict(zip(user_last_item_created_time['user_id'],user_last_item_created_time['created_at_ts']))

    return user_hist_item_types_dict,user_hist_item_ids_dict,user_hist_item_words_dict,user_last_item_created_time_dict

In [15]:
item_type_dict,item_words_dict,item_created_time_dict=get_item_info_dict(item_info_df)

In [16]:
# 定义一个多路召回的字典，将各路召回的结果都保存在这个字典当中
user_multi_recall_dict={'itemcf_sim_itemcf_recall':{},'embedding_sim_item_recall':{},'youtubednn_recall':{},'youtubednn_usercf_recall':{},'cold_start_recall':{}}

In [17]:
trn_hist_click_df,trn_last_click_df=get_hist_and_last_click(all_click_df)

In [18]:
trn_last_click_df

,user_id,click_article_id,click_timestamp,click_environment,click_deviceGroup,click_os,click_country,click_region,click_referrer_type
1112620,0,157507,0.597140,4,1,17,1,25,2
1112103,63,205824,0.596085,4,3,2,1,25,2
1112020,67,5595,0.595958,4,3,2,1,21,5
1111806,98,211455,0.595648,4,1,17,1,25,2
1111756,103,284470,0.595531,4,1,12,1,25,2
...,...,...,...,...,...,...,...,...,...
501584,199901,236553,0.271168,4,3,2,1,8,2
1021206,199948,218028,0.549133,4,1,17,1,2,2
1043811,199951,331116,0.568751,4,1,17,1,25,2
1041660,199961,336254,0.568413,4,1,17,1,20,1
1069757,199995,277107,0.576672,4,1,17,1,25,5

In [19]:
def metrics_recall(user_recall_items_dict,trn_last_click_df,topk=5):
    # 对召回的结果评估
    last_click_item_dict=dict(zip(trn_last_click_df['user_id'],trn_last_click_df['click_article_id']))
    user_num=len(user_recall_items_dict)
    for k in range(10,topk+1,10):
        hit_num=0
        for user ,item_list in user_recall_items_dict.items():
            tmp=[x[0] for x in user_recall_items_dict[user][:k]]
            if last_click_item_dict[user] in set(tmp):
                hit_num+=1
        hit_rate=round(hit_num*10/user_num,5)
        print(' topk: ', k, ' : ', 'hit_num: ', hit_num, 'hit_rate: ', hit_rate, 'user_num : ', user_num)

# 3.计算相似度矩阵

In [20]:
def itemcf_sim(df,item_created_time_dict):
    '''计算物品的相似度矩阵,使用关联规则考虑了1. 用户点击的时间权重 2. 用户点击的顺序权重 3. 文章创建的时间权重'''
    user_item_time_dict =get_user_item_time(df)
    # i2i_sim[i][j]统计i和j共有的受众个数
    i2i_sim=defaultdict(dict)
    # 统计每个物品受众个数
    item_cnt=defaultdict(int)
    for user,item_time_list in tqdm(user_item_time_dict.items()):
        for loc1,(i,i_click_time) in enumerate(item_time_list.items()):
            # 更新
            item_cnt[i]+=1
            for loc2,(j, j_click_time) in enumerate(item_time_list.items()):
                if i!=j:
                    # 考虑文章的正向顺序点击和反向顺序点击
                    loc_alpha=1.0 if loc2>loc1 else 0.7
                    # 位置信息的权重
                    loc_weight=loc_alpha*(0.9**(np.abs(loc2-loc1)-1))
                    # 点击时间的权重
                    click_time_weight=np.exp(0.7**np.abs(i_click_time-j_click_time))
                    # 创建时间的权重
                    created_time_weight=np.exp(0.8**np.abs(item_created_time_dict[i]-item_created_time_dict[j]))
                    i2i_sim[i].setdefault(j,0)
                    # 加权弱化：用户点击的物品越多，对每对物品的贡献就越小
                    i2i_sim[i][j]+=loc_weight*click_time_weight*created_time_weight/math.log(len(item_time_list)+1)
    i2i_sim_=i2i_sim.copy()

    for i, related_items in i2i_sim.items():
        for j, wij in related_items.items():
            i2i_sim_[i][j]=wij/math.sqrt(item_cnt[i]*item_cnt[j])
    # 保存相似度矩阵
    pickle.dump(i2i_sim_, open('./save/itemcf_i2i_sim.pkl', 'wb'))
    return i2i_sim_

In [21]:
i2i_sim=itemcf_sim(all_click_df,item_created_time_dict)

100%|██████████| 10000/10000 [00:05<00:00, 1686.22it/s]

In [22]:
all_click_df.groupby('user_id')['click_article_id'].count()

user_id
0          2
63         2
67         2
98         2
103        2
          ..
199901     6
199948     7
199951    11
199961    24
199995     7
Name: click_article_id, Length: 10000, dtype: int64

In [23]:
def get_user_activate_degree_dict(all_click_df):
    '''获取用户活跃度'''
    all_click_df_=all_click_df.groupby('user_id')['click_article_id'].count().reset_index()

    # 归一化
    mm=MinMaxScaler()
    all_click_df_['click_article_id']=mm.fit_transform(all_click_df_[['click_article_id']])

    user_activate_degree_dict = dict(zip(all_click_df_['user_id'],all_click_df_['click_article_id']))

    return user_activate_degree_dict

In [24]:
def usercf_sim(all_click_df,user_activate_degree_dict):
    '''用户相似度计算'''
    item_user_time_dict=get_item_user_time(all_click_df)
    u2u_sim=defaultdict(dict)
    user_cnt=defaultdict(int)
    for item,user_time_list in tqdm(item_user_time_dict.items()):
        for u,click_time in user_time_list.items():
            user_cnt[u]+=1
            for v,click_time in user_time_list.items():
                u2u_sim[u].setdefault(v,0)
                if u!=v:
                    activate_weight=100*0.5*(user_activate_degree_dict[u]+user_activate_degree_dict[v])
                    u2u_sim[u][v]+=activate_weight/math.log(len(user_time_list)+1)
    u2u_sim_=u2u_sim.copy()
    for u,relater_users in u2u_sim.items():
        for v,wij in relater_users.items():
            u2u_sim_[u][v]=wij/math.sqrt(user_cnt[u]*user_cnt[v])
    pickle.dump(u2u_sim_,open('./save/usercf_u2u_sim.pkl', 'wb'))
    return u2u_sim_

In [25]:
user_activate_degree_dict=get_user_activate_degree_dict(all_click_df)
u2u_sim=usercf_sim(all_click_df,user_activate_degree_dict)

100%|██████████| 6519/6519 [00:09<00:00, 706.20it/s]

In [29]:
def embdding_sim(click_df,item_emb_df,topk):
    '''基于文章的embedding计算相似度'''

    # 文章索引与文章id的字典映射
    item_idx_2_rawid_dict=dict(zip(item_emb_df.index,item_emb_df['article_id']))

    item_emb_cols=[x for x in item_emb_df.columns if 'emb' in x]
    item_emb_np=np.ascontiguousarray(item_emb_df[item_emb_cols].values,dtype=np.float32)
    item_emb_np=item_emb_np/np.linalg.norm(item_emb_np,axis=1,keepdims=True)

    # 建立faiss索引，基于内积
    item_index=faiss.IndexFlatIP(item_emb_np.shape[1])
    # 添加向量
    item_index.add(item_emb_np)
    # 为所有物品做一次批量检索，哈走出最相似的k个物品
    sim,idx=item_index.search(item_emb_np,topk)

    item_sim_dict=defaultdict(dict)
    for target_index,sim_value_list,rele_idx_list in tqdm(zip(range(len(item_emb_np)),sim,idx),total=len(item_emb_np)):
        # sim_value_list,rele_idx_list对当前物品所对的最相似的物品及其相似度
        target_raw_id=item_idx_2_rawid_dict[target_index]
        # 首位是物品本身
        for rele_idx,sim_value in zip(rele_idx_list[1:],sim_value_list[1:]):
            rele_raw_id=item_idx_2_rawid_dict[rele_idx]
            item_sim_dict[target_raw_id][rele_raw_id]=sim_value

    pickle.dump(item_sim_dict,open('./save/emb_i2i_sim.pkl','wb'))
    return item_sim_dict

In [27]:
pd.read_csv('./data/articles_emb.csv')

,article_id,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,emb_7,emb_8,...,emb_240,emb_241,emb_242,emb_243,emb_244,emb_245,emb_246,emb_247,emb_248,emb_249
0,0,-0.161183,-0.957233,-0.137944,0.050855,0.830055,0.901365,-0.335148,-0.559561,-0.500603,...,0.321248,0.313999,0.636412,0.169179,0.540524,-0.813182,0.286870,-0.231686,0.597416,0.409623
1,1,-0.523216,-0.974058,0.738608,0.155234,0.626294,0.485297,-0.715657,-0.897996,-0.359747,...,-0.487843,0.823124,0.412688,-0.338654,0.320786,0.588643,-0.594137,0.182828,0.397090,-0.834364
2,2,-0.619619,-0.972960,-0.207360,-0.128861,0.044748,-0.387535,-0.730477,-0.066126,-0.754899,...,0.454756,0.473184,0.377866,-0.863887,-0.383365,0.137721,-0.810877,-0.447580,0.805932,-0.285284
3,3,-0.740843,-0.975749,0.391698,0.641738,-0.268645,0.191745,-0.825593,-0.710591,-0.040099,...,0.271535,0.036040,0.480029,-0.763173,0.022627,0.565165,-0.910286,-0.537838,0.243541,-0.885329
4,4,-0.279052,-0.972315,0.685374,0.113056,0.238315,0.271913,-0.568816,0.341194,-0.600554,...,0.238286,0.809268,0.427521,-0.615932,-0.503697,0.614450,-0.917760,-0.424061,0.185484,-0.580292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364042,364042,-0.055038,-0.962136,0.869436,-0.071523,-0.725294,0.434320,0.198312,-0.581154,0.702346,...,-0.410550,0.564253,-0.463959,0.167907,-0.480068,0.652090,0.380880,0.433195,-0.662455,-0.222850
364043,364043,-0.136932,-0.995471,0.991298,0.031871,-0.915621,-0.658517,0.633090,-0.564356,0.676551,...,-0.681986,-0.574185,-0.536908,0.688934,0.528204,0.162435,0.940364,0.989298,-0.761595,-0.414652
364044,364044,-0.251390,-0.976243,0.586097,0.643631,-0.663359,-0.093480,0.691554,-0.588281,0.902999,...,-0.162220,-0.242030,-0.476131,0.352132,-0.311279,0.460574,-0.653077,-0.143725,0.068093,-0.705010
364045,364045,0.224342,-0.923288,-0.381742,0.687890,-0.773911,-0.103629,-0.406486,0.246004,0.255191,...,-0.422999,0.390324,0.655911,-0.646753,-0.174031,0.698037,-0.317102,0.687132,-0.531512,0.010726
364046,364046,-0.257134,-0.994631,0.983792,-0.190975,-0.953720,-0.893823,0.708974,-0.557027,0.846842,...,-0.490481,-0.689666,-0.661846,0.490945,0.736526,0.667668,0.902130,0.983873,-0.838183,-0.179283

In [28]:
item_emb_dict

{0: array([-0.02118425, -0.12580893, -0.01813001,  0.00668391,  0.10909397,
         0.11846624, -0.04404838, -0.07354293, -0.06579412,  0.02170995,
         0.05630901,  0.04666488,  0.11492702, -0.06951095,  0.08220764,
         0.03534407, -0.10814503, -0.09250724, -0.08225472, -0.02008969,
        -0.08756393,  0.00569023,  0.02347829,  0.00616275,  0.07813909,
        -0.02409734,  0.02564285, -0.06146177, -0.04006071,  0.04641773,
         0.03656221,  0.07079111, -0.04878796,  0.06438719, -0.01364673,
         0.01566297,  0.01740611, -0.08162891, -0.0595786 ,  0.04555704,
        -0.00811461, -0.09602179, -0.05048424, -0.12364366,  0.00806219,
         0.06342559,  0.038073  , -0.08184084, -0.00657207,  0.05539924,
        -0.03188176,  0.08788847, -0.06689828, -0.06069421,  0.00577   ,
         0.03791584,  0.05912034, -0.03743939,  0.12048548,  0.09241205,
         0.11193531, -0.08243855,  0.04701659,  0.0512825 ,  0.08581513,
         0.01362305,  0.10491944, -0.01347765, -0.02687927,  0.04976083,
        -0.01186304, -0.03300955,  0.04284385,  0.0112872 , -0.0237316 ,
         0.00624597, -0.02099457, -0.08150581,  0.03947292, -0.10468995,
         0.06278647,  0.05387553,  0.04308082,  0.00953796, -0.11084635,
         0.07548293,  0.04353037,  0.09662702, -0.00672256, -0.0553719 ,
        -0.11848808, -0.0401216 , -0.01781782, -0.06153216, -0.03371358,
        -0.00368468,  0.03873509, -0.00885146, -0.06065871,  0.00948037,
        -0.07501019, -0.00788365, -0.07233528, -0.07938115,  0.05290344,
        -0.04028066,  0.04346518,  0.01870665,  0.04375365,  0.03081685,
         0.09077243,  0.06391993,  0.05616949, -0.01524274,  0.05065336,
         0.05200844, -0.08655743, -0.07307556,  0.10284474,  0.01692638,
         0.08557871, -0.02738355, -0.06605549,  0.05542525, -0.04139032,
        -0.00360723, -0.03212789,  0.10635407,  0.02468561,  0.02128577,
        -0.01971008, -0.09390406, -0.00091728, -0.04112654,  0.12415481,
         0.03156857, -0.02259784, -0.09373021,  0.00191951,  0.03940221,
        -0.09514481, -0.04947353,  0.08972952, -0.07933075, -0.07538353,
        -0.06339155, -0.08872179,  0.01653261, -0.0108014 , -0.0614667 ,
         0.11471707,  0.0470121 ,  0.10502738, -0.10384496,  0.06529624,
         0.07470956, -0.04571309,  0.08547449, -0.07872635,  0.05538737,
         0.01411314, -0.06049801,  0.03966642, -0.05249816, -0.00458397,
         0.01619317, -0.00023619, -0.02826874, -0.05372207,  0.02690729,
        -0.07933813, -0.02952798, -0.05535949,  0.08505901, -0.04343209,
        -0.03820711, -0.00704694,  0.06786877,  0.04339524,  0.04942733,
        -0.02315485, -0.07460886, -0.0013101 , -0.05261767, -0.06544498,
        -0.0297435 , -0.07569498, -0.04803508,  0.0384174 ,  0.09054015,
         0.11461206, -0.00750561, -0.04067157, -0.05622186, -0.09056782,
         0.08594477, -0.05492759, -0.01713211, -0.12340462, -0.08030416,
         0.07438132, -0.00036778, -0.00609367,  0.0780876 ,  0.02229499,
         0.03293534, -0.00825679, -0.05341626,  0.02309523, -0.03403827,
         0.10046245,  0.03622786, -0.09096757, -0.05168346, -0.04280575,
         0.02147263, -0.02036532, -0.09221629,  0.093555  , -0.11027785,
        -0.0603453 ,  0.12090397,  0.08172744, -0.084177  ,  0.05124897,
         0.10043571,  0.02166635, -0.09818101,  0.05402212,  0.09869072,
         0.11311417,  0.08079711,  0.07224165,  0.043955  , -0.0510025 ,
        -0.09249106, -0.07457595,  0.00085146, -0.0271521 , -0.05063617,
         0.04222158,  0.04126878,  0.08364352,  0.0222351 ,  0.07104095,
        -0.10687634,  0.0377033 , -0.03045044,  0.07851824,  0.05383667]),
 1: array([-0.06498079, -0.12097317,  0.09173146,  0.01927935,  0.07778261,
         0.06027149, -0.08888102, -0.11152663, -0.04467875,  0.0494602 ,
         0.08356338, -0.00138849, -0.04315851, -0.06723248,  0.05694242,
         0.05990129,  0.08863364, -0.05887461,  0.05039675,  0.08338836,
        -0.05971998,  0.05399734,  0.05818527,  0.04674996,  0.04570973,
         0.02391308,  0.01186958, -0.0673428 ,  0.00814067,  0.04511596,
        -0.02021945,  0.0396948 ,  0.05830619,  0.0718426 , -0.09980769,
        -0.03782299,  0.07892728,  0.01117486, -0.07078446,  0.01270608,
        -0.02548841, -0.07586899, -0.06228485, -0.11928686, -0.0075256 ,
         0.04749456, -0.03693161,  0.05082863, -0.02705765,  0.06189225,
        -0.07635018,  0.10485507,  0.08447388, -0.01985978,  0.00766718,
         0.01793794,  0.03945281,  0.03067727,  0.11722423, -0.04726628,
         0.11408478, -0.10588934, -0.02091164,  0.09369785, -0.01772661,
         0.05224176, -0.05414424, -0.01293588,  0.0124265 , -0.05898841,
        -0.00341418,  0.11074253, -0.01174819, -0.09710336,  0.03878365,
        -0.05053624,  0.04896493, -0.08918869, -0.08055439,  0.0320939 ,
         0.02332274, -0.10245294,  0.03854215,  0.05428281, -0.05923058,
        -0.05536764,  0.05088271,  0.07506041, -0.04492041, -0.04628881,
         0.02814642, -0.07945122,  0.08290194, -0.10208213,  0.05475915,
         0.00263873,  0.03830134, -0.04175772,  0.02855523,  0.01677929,
         0.01868126, -0.09672384, -0.02029872, -0.03754595,  0.03994736,
         0.10690982, -0.01048548, -0.05172177,  0.00309404,  0.01940745,
        -0.042687  ,  0.10761483,  0.02659099,  0.08532522,  0.1059384 ,
         0.01053193, -0.06415953, -0.10658304, -0.06767883,  0.05020549,
         0.06076507, -0.00862761,  0.0400436 ,  0.0424081 ,  0.0434777 ,
        -0.00116645,  0.09617592,  0.11220514, -0.08091692, -0.02744062,
        -0.10614041, -0.04241469,  0.06087706,  0.10446053,  0.11999189,
         0.07981133,  0.07747514,  0.01799468,  0.05790624,  0.04829908,
        -0.10999084,  0.06370201, -0.041662  ,  0.08582252, -0.04970988,
         0.00851067, -0.00452521, -0.08274356, -0.07799751,  0.02417545,
         0.11596007, -0.10786465,  0.02990218, -0.06295816, -0.05514397,
         0.06020027,  0.03428738,  0.02997861, -0.03143384, -0.03682834,
        -0.03815093,  0.08554395,  0.06257868,  0.04400719, -0.03133554,
        -0.06885722, -0.03527225, -0.072421  ,  0.08922033, -0.08859026,
        -0.04284444, -0.0478904 ,  0.04975765,  0.06289742,  0.03916921,
         0.09932139, -0.0277925 , -0.09877244,  0.03737846, -0.04257543,
        -0.0129629 , -0.04324991, -0.02601823, -0.04251682, -0.09082053,
         0.01895996, -0.02864675, -0.00881573, -0.11014227, -0.08809449,
         0.01819643, -0.02282518,  0.00197034, -0.00323131,  0.01192864,
        -0.06111632,  0.01981428,  0.03070028, -0.11986671, -0.05018481,
         0.04900745, -0.07001217, -0.11122481,  0.08681161,  0.08045704,
        -0.06036205, -0.0834186 ,  0.00272385, -0.00684369, -0.0506288 ,
         0.04276294, -0.06632635,  0.09050888,  0.10682138, -0.00349809,
         0.06099389,  0.06601661,  0.06772978, -0.02999856, -0.01131647,
         0.00020182,  0.11809988, -0.04567954, -0.02675292, -0.01638023,
         0.08806432,  0.0761162 ,  0.10120466,  0.03461068,  0.00045831,
        -0.03561581, -0.01253571, -0.04751767, -0.02383125, -0.0517173 ,
        -0.10638463,  0.06674759,  0.03498485, -0.08467981,  0.08272564,
        -0.06058773,  0.10222798,  0.05125378, -0.0420592 ,  0.03984009,
         0.07310649, -0.07378883,  0.02270635,  0.04931655, -0.10362383]),
 2: array([-0.08056885, -0.1265138 , -0.02696299, -0.01675577,  0.00581852,
        -0.05039108, -0.09498371, -0.00859836, -0.09815931, -0.03146776,
         0.08718287, -0.03645882, -0.07246363, -0.01094136,  0.00361248,
         0.0382384 ,  0.04716144, -0.04792239,  0.0192392 , -0.00152796,
         0.00392803,  0.01382436,  0.08166035,  0.05056194,  0.08008674,
        -0.05787794,  0.01378681,  0.01782831, -0.01242246,  0.04453936,
         0.07706168, -0.03404061,  0.04448611,  0.09161106, -0.05631157,
         0.01354316,  0.1021996 ,  0.07654074, -0.08161803, -0.0186325 ,
         0.05199   , -0.09209156, -0.09530713, -0.12459994, -0.08183098,
        -0.03669959,  0.00717602, -0.09223071,  0.07550222, -0.06739809,
         0.0076772 ,  0.0863834 ,  0.04814226, -0.02916172, -0.02960397,
         0.09030183,  0.02184099,  0.01307898,  0.12312216, -0.06173896,
         0.11860938, -0.05699134, -0.00600424,  0.10498534, -0.03612413,
        -0.07804487, -0.0658783 , -0.00106643, -0.10699986,  0.02610735,
         0.03815985,  0.07922095, -0.08238501, -0.09828704, -0.02621975,
        -0.10569618, -0.03691637, -0.10841882, -0.07780939, -0.00718963,
         0.00578961, -0.04352928,  0.06776194, -0.04733136, -0.08982972,
        -0.10418505,  0.07195463,  0.09663843, -0.05575297, -0.06259235,
        -0.06620808,  0.0030089 , -0.08905872, -0.01706784,  0.04968007,
         0.0182864 ,  0.05848216, -0.07505225,  0.05207391, -0.10130233,
         0.01917245, -0.02505019, -0.08504267, -0.02989607,  0.0314551 ,
         0.05762482,  0.04826374, -0.00378127,  0.07523801,  0.04160796,
        -0.07245524,  0.11178218,  0.00388978,  0.10634753,  0.05410111,
         0.03780479,  0.01670168, -0.09070027, -0.03490928,  0.02922255,
        -0.00541052,  0.08499508,  0.08434281, -0.01054416,  0.03354551,
        -0.01692026,  0.06853067,  0.11561234, -0.05969067,  0.02643448,
        -0.10024589, -0.0407948 ,  0.02675255,  0.08926725,  0.12497577,
         0.02625193, -0.03650732,  0.08653637, -0.06172963,  0.0982544 ,
        -0.11071772, -0.02586685, -0.07367064,  0.00158779, -0.01967672,
         0.06167651, -0.00342215,  0.04116785, -0.03498357, -0.06802453,
         0.11936982, -0.00130591,  0.07267299, -0.07170544, -0.00826898,
        -0.0280459 , -0.01347199, -0.01357757, -0.0289616 , -0.02197763,
         0.07019287, -0.00349004,  0.04278496,  0.09061084,  0.0296485 ,
        -0.02452672,  0.07777156, -0.08555013,  0.0393444 ,  0.0459961 ,
        -0.06044193, -0.07894806,  0.1038184 ,  0.11352486, -0.00804699,
         0.09874119,  0.01056118, -0.01759615,  0.00890421, -0.00839267,
         0.03348854, -0.07652139,  0.02259125,  0.03280459, -0.05837272,
         0.06879743,  0.01751793, -0.02102784, -0.03996964,  0.02015549,
        -0.07544244,  0.04332518, -0.06981425, -0.00858777, -0.00540207,
        -0.01856585,  0.05359237, -0.08105193, -0.12551549,  0.07795078,
         0.0672921 ,  0.06086482, -0.09697271, -0.0186038 , -0.00829252,
         0.00446981, -0.10637299,  0.05695217, -0.02503992,  0.05376562,
        -0.07812713, -0.070128  ,  0.05437797,  0.00373385,  0.01755502,
        -0.04076213,  0.09678905, -0.01886907, -0.06312737, -0.07691972,
         0.00391548,  0.12388401, -0.07403587, -0.04676912,  0.07303459,
         0.04962863, -0.02461465,  0.05473597,  0.00290453, -0.04285249,
         0.03026633,  0.05518048, -0.06301222,  0.05127628, -0.04284837,
        -0.11082344,  0.08256781, -0.06926335, -0.06103548,  0.09297007,
         0.05913178,  0.06152799,  0.04913376, -0.11233104, -0.04984886,
         0.01790787, -0.1054381 , -0.05819875,  0.1047951 , -0.03709542]),
 3: array([-0.08898244, -0.11719687,  0.04704669,  0.0770789 , -0.03226681,
         0.02303047, -0.09916173, -0.08534883, -0.00481633, -0.0132738 ,
         0.07106171, -0.02945151, -0.0946966 , -0.04147301, -0.09085177,
         0.01694927,  0.03408502, -0.04443561,  0.04500909,  0.11081717,
         0.02068513,  0.03045766,  0.06631346, -0.05454556,  0.04626148,
        -0.01814865,  0.07189276, -0.07377016, -0.03108021,  0.07109369,
         0.07431779,  0.04979722,  0.08385865, -0.01379606, -0.00829426,
        -0.05050067,  0.07078881,  0.05968829, -0.0540142 , -0.08973545,
        -0.0556221 ,  0.01461142, -0.04342362, -0.11536811, -0.03756301,
        -0.03411165, -0.00578951, -0.05715418, -0.010803  , -0.07688117,
        -0.03965486, -0.02331106,  0.05427083,  0.02425218, -0.02474417,
        -0.00987877, -0.05512646,  0.03943755,  0.11394049, -0.02530078,
         0.1116467 ,  0.01362835, -0.0341384 ,  0.02911499, -0.07710369,
         0.0199324 , -0.07628553,  0.02787928,  0.04860047, -0.03913662,
         0.05146751,  0.06603466, -0.04153557, -0.05178552, -0.0073548 ,
        -0.07462382, -0.07711393, -0.07539627, -0.03467778,  0.03363004,
         0.02194342,  0.04976588,  0.09108757,  0.08866299, -0.03221465,
        -0.1148456 ,  0.07370234,  0.04419546, -0.05835523, -0.07093179,
         0.03950179,  0.05137966, -0.07103775, -0.08120114,  0.08883999,
        -0.03569011, -0.00018281,  0.07287756,  0.00254066, -0.02401506,
         0.07197983, -0.11214023, -0.08815236, -0.04262634, -0.01225272,
         0.06326793,  0.04801509, -0.09346507,  0.05428335,  0.0734238 ,
        -0.07644996,  0.09890062,  0.03142118,  0.08082252,  0.088614  ,
         0.10269002,  0.03358754, -0.05441164, -0.04344385, -0.03925157,
        -0.06586241,  0.09883164,  0.03378871, -0.06193768,  0.03883013,
        -0.06840599,  0.08734728,  0.11007277,  0.00624043,  0.09112201,
        -0.07822865,  0.02074875, -0.01778731,  0.04361668,  0.11608106,
        -0.08404975, -0.01323899,  0.0737671 , -0.07608989,  0.06118698,
        -0.10674504, -0.04364125, -0.0525345 , -0.00407716, -0.01264537,
        -0.00959492, -0.03927522,  0.07351882,  0.02618966, -0.06716211,
         0.1128343 , -0.09674125, -0.01775117, -0.0735821 , -0.07157135,
        -0.04213541,  0.02159484,  0.01039185,  0.07422888, -0.08655519,
         0.05917454,  0.07258802, -0.08619728,  0.02284465, -0.01980155,
        -0.05127101, -0.05519446, -0.07374393,  0.07141405, -0.11051957,
        -0.09476325, -0.06210372,  0.0736203 ,  0.02739516, -0.05543813,
         0.08394047, -0.01795952, -0.09238862, -0.10893311, -0.06404005,
        -0.03367709, -0.0923637 ,  0.04799056,  0.06874508, -0.0999655 ,
         0.01206513,  0.10535468, -0.08309442, -0.11594319, -0.04271567,
        -0.10317759,  0.01305698, -0.08967571, -0.00397073,  0.03572216,
        -0.03009061,  0.04178377,  0.06267917, -0.11621353, -0.01451066,
        -0.00085739,  0.0538312 ,  0.01326522,  0.02144305, -0.02884189,
         0.04633236, -0.10443559,  0.04486223,  0.03952804, -0.00396057,
        -0.01646954, -0.02948574,  0.02048575,  0.06823303, -0.03030309,
        -0.05473713,  0.09089479,  0.07526251, -0.00064845, -0.05673443,
         0.03899065,  0.11462608, -0.10095855, -0.09612761,  0.01340871,
        -0.06027176,  0.01393101,  0.09678915, -0.00498225,  0.03851074,
        -0.05406294, -0.0454855 ,  0.06120976,  0.01715005,  0.01797681,
        -0.10763997,  0.02815233, -0.02280057, -0.071779  ,  0.0316858 ,
         0.03261397,  0.00432879,  0.05765608, -0.09166448,  0.00271771,
         0.06788175, -0.10933413, -0.06459955,  0.02925163, -0.10633652]),
 4: array([-0.03511259, -0.12234483,  0.08623944,  0.01422566,  0.0299868 ,
         0.03421434, -0.07157316,  0.04293183, -0.07556672, -0.01580963,
         0.08791226,  0.05882519, -0.09319656, -0.03247151, -0.01184167,
         0.03233044,  0.07324108, -0.00315086,  0.04267647, -0.04384774,
         0.05197667,  0.02012565,  0.06431556,  0.07650449,  0.07879691,
        -0.06803414,  0.07847161, -0.00247849,  0.00347378, -0.02974203,
         0.03921708, -0.07044264,  0.09643251,  0.0519109 , -0.08346673,
         0.01945635,  0.08910312,  0.02704732, -0.10443292, -0.10122769,
        -0.00090772, -0.04578531, -0.06204104, -0.12059141, -0.08125146,
        -0.01199855, -0.09057973, -0.00911763, -0.06057922,  0.00054333,
        -0.00213552,  0.06374168,  0.09563862, -0.01604138, -0.06430593,
         0.06818938, -0.03413678,  0.0695622 ,  0.11792956, -0.10196453,
         0.11293206, -0.02767271, -0.00564665,  0.09369988, -0.00329555,
        -0.01133497, -0.09598748, -0.01180229, -0.08238687, -0.0516509 ,
         0.04861392,  0.11207221, -0.00428579, -0.10806047,  0.03346421,
        -0.08878327, -0.07437407, -0.07241126,  0.03123883, -0.04165494,
        -0.02440611, -0.06083581,  0.07718882,  0.05165113, -0.04175363,
        -0.019385  ,  0.05707031,  0.05807467, -0.09816736,  0.0236538 ,
         0.07883568, -0.02558349,  0.00197491, -0.06830623,  0.03262179,
         0.03648527,  0.02637085, -0.03655748,  0.0342865 , -0.07563463,
        -0.00180042, -0.07028016, -0.0852526 , -0.06061165,  0.04606029,
         0.08663451,  0.01408372, -0.054078  ,  0.06820409,  0.02513276,
        -0.09961206,  0.09650085, -0.04717777,  0.07860032,  0.08117315,
         0.04457398,  0.01725012, -0.01811001, -0.01469187, -0.0021684 ,
        -0.0299872 ,  0.05264285,  0.07803132, -0.04264872, -0.00083431,
         0.01398367,  0.08968123,  0.11134487, -0.06751348,  0.02823456,
        -0.09992885,  0.09270251,  0.02276664,  0.099789  ,  0.12078537,
         0.02110773,  0.04314579,  0.04221924, -0.02305968,  0.10718378,
        -0.10482647, -0.0160479 , -0.01813908, -0.06361968, -0.043639  ,
         0.03357633, -0.07534836,  0.08799332, -0.04823378,  0.00419956,
         0.11318222, -0.02410033,  0.01280174, -0.0640761 , -0.02443832,
         0.0707194 ,  0.03851702, -0.06445648,  0.06846251, -0.0932599 ,
        -0.06476602,  0.02739358,  0.02373327,  0.0392271 , -0.02009352,
        -0.03342087, -0.01414711, -0.07493037,  0.08797455,  0.08568277,
         0.06242658, -0.05117293,  0.0936567 ,  0.09899135, -0.06136438,
         0.06992356,  0.03381628, -0.07323497,  0.02603248, -0.10279368,
        -0.01257604, -0.07270342, -0.07215521,  0.00251172, -0.06914316,
        -0.01544107,  0.085044  ,  0.01709815, -0.0616783 , -0.10015143,
        -0.06596219, -0.0062113 , -0.0148462 ,  0.03924345, -0.05326553,
        -0.05305523,  0.01698164, -0.00450239, -0.12069991,  0.07154211,
        -0.00743974, -0.02057561, -0.08935994,  0.01562331,  0.07372667,
         0.03861349, -0.08590062,  0.02530521, -0.04707002,  0.02684287,
         0.0294974 , -0.08672517,  0.09451639,  0.08146425, -0.00423173,
        -0.07280648,  0.1032944 ,  0.04660389, -0.06652775, -0.06748275,
        -0.01111677,  0.11883725, -0.11169518, -0.07768108,  0.0320346 ,
         0.01061251,  0.03603301,  0.04538799,  0.04650979, -0.05694275,
        -0.03686292, -0.06669198, -0.02983685,  0.02931899,  0.00032831,
        -0.10508491,  0.06217644,  0.00371635, -0.07796805,  0.10235439,
         0.02998313,  0.10182882,  0.05379428, -0.07750169, -0.06337934,
         0.07731525, -0.11548023, -0.05335886,  0.02333915, -0.07301722]),
 5: array([-0.08791854, -0.11820671,  0.0139168 ,  0.016493  , -0.00717088,
         0.01689343, -0.08742135, -0.03775659, -0.06593112,  0.07443181,
         0.09242073,  0.08608337, -0.08929429, -0.04893885,  0.02074046,
        -0.03608444,  0.10605541, -0.03702142,  0.04854535, -0.05328814,
         0.00803838, -0.0230776 ,  0.06710483,  0.07099115,  0.10138936,
        -0.0510277 ,  0.07968546,  0.01793626, -0.08262708,  0.05021542,
         0.04296213, -0.06498673,  0.08609772,  0.0049693 , -0.07923117,
         0.00252149,  0.02480344,  0.07281319, -0.0800953 , -0.08703125,
        -0.04844941, -0.0098252 , -0.04031313, -0.11681615, -0.10317848,
        -0.01285354,  0.04718786,  0.02534203, -0.00826446,  0.01880336,
        -0.06491033,  0.08960905,  0.06100405,  0.00283511, -0.07936365,
         0.00738403,  0.01166219,  0.05466959,  0.11519534, -0.0856927 ,
         0.11339397, -0.0590788 ,  0.0226093 ,  0.09435896, -0.01529333,
        -0.00482671, -0.03143785, -0.07112403, -0.04986159, -0.09123034,
         0.01233423,  0.10782916, -0.00405239, -0.09489394, -0.00794672,
        -0.07997602,  0.01220979, -0.0822064 , -0.01028699, -0.00054337,
        -0.02984917, -0.02491791,  0.10145652,  0.02368779, -0.07471183,
        -0.04847458,  0.07858849,  0.10102338, -0.08896554, -0.05463696,
         0.06502648, -0.06794666, -0.02073122, -0.06687998,  0.06238611,
         0.05312618, -0.03030389, -0.02363256,  0.0244812 , -0.05481426,
        -0.03117023, -0.09156174, -0.09155923, -0.09325152,  0.01373249,
         0.06835622,  0.01375816, -0.08180541,  0.02028254,  0.04184124,
        -0.06163638,  0.1087215 , -0.03650775,  0.09930791,  0.0691075 ,

In [30]:
item_emb_df=pd.read_csv('./data/articles_emb.csv').sample(10000,random_state=0).reset_index(drop=True)
emb_i2i_sim=embdding_sim(all_click_df,item_emb_df,topk=10)

100%|██████████| 10000/10000 [00:00<00:00, 165807.02it/s]

# 4.召回

## youtubeDnn召回

In [ ]:
def gen_data_set(data,negsample=0):
    '''获取youtubeDnn召回召回时的训练和验证数据，这里进行负采样'''
    data.sort_values('click_timestamp',inplace=True)
    item_ids=data['click_article_id'].unique()

    # 数据的格式 [user_id, 交互过的历史物品, 下一个要交互的物品, 正/负本, 历史行为的长度]
    train_set=[]
    test_set=[]

    for reviewerID, hist in tqdm(data.groupby('user_id')):
        pos_list=hist['click_article_id'].tolist()

        # 用户交互过的物品只有一个也要放到训练集中，否则会造成embedding缺失
        if len(pos_list)==1:
            train_set.append((reviewerID,[pos_list[0]],pos_list[0],1,len(pos_list)))
            test_set.append((reviewerID,[pos_list[0]],pos_list[0],1,len(pos_list)))

        if negsample>0:
            candidate_set=list(set(item_ids)-set(pos_list))
            neg_list=np.random.choice(candidate_set,size=len(pos_list)*negsample,replace=False)# 为每个正样本抽取n个负样本，replace控制是否可以放回抽样
        for i in range(1,len(pos_list)):
            hist=pos_list[:i] # 历史物品
            if i!=len(pos_list)-1:
                train_set.append((reviewerID,hist[::-1],pos_list[i],1,len(hist)))
                for negi in range(negsample):
                    train_set.append((reviewerID,hist[::-1],neg_list[i*negsample+negi],0,len(hist)))
            else:
                # 最长的序列作为测试数据
                test_set.append((reviewerID,hist[::-1],pos_list[i],1,len(hist)))
    random.shuffle(train_set)
    random.shuffle(test_set)
    return train_set,test_set