In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

In [40]:
articles_path='../data/articles.csv'
customer_path='../data/customers.csv'
transaction_path='../data/transactions_train.csv'

In [53]:
articles=pd.read_csv(articles_path)
customers=pd.read_csv(customer_path)
transactions=pd.read_csv(transaction_path)

# articles

In [5]:
articles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105542 entries, 0 to 105541
Data columns (total 25 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   article_id                    105542 non-null  int64
 1   product_code                  105542 non-null  int64
 2   prod_name                     105542 non-null  object
 3   product_type_no               105542 non-null  int64
 4   product_type_name             105542 non-null  object
 5   product_group_name            105542 non-null  object
 6   graphical_appearance_no       105542 non-null  int64
 7   graphical_appearance_name     105542 non-null  object
 8   colour_group_code             105542 non-null  int64
 9   colour_group_name             105542 non-null  object
 10  perceived_colour_value_id     105542 non-null  int64
 11  perceived_colour_value_name   105542 non-null  object
 12  perceived_colour_master_id    105542 non-null  int64
 13  perceived_colour_master_name  105542 non-null  object
 14  department_no                 105542 non-null  int64
 15  department_name               105542 non-null  object
 16  index_code                    105542 non-null  object
 17  index_name                    105542 non-null  object
 18  index_group_no                105542 non-null  int64
 19  index_group_name              105542 non-null  object
 20  section_no                    105542 non-null  int64
 21  section_name                  105542 non-null  object
 22  garment_group_no              105542 non-null  int64
 23  garment_group_name            105542 non-null  object
 24  detail_desc                   105126 non-null  object
dtypes: int64(11), object(14)
memory usage: 20.1+ MB

这张表包含了 H&M 所有商品及其详细信息，如产品类型、颜色、产品组以及其他特征。

**商品数据说明：**

* **article_id**：每件商品的唯一标识符。
* **product_code, prod_name**：款式的唯一标识符及其名称。
* **product_type, product_type_name**：产品代码所属的类别及其名称。
* **graphical_appearance_no, graphical_appearance_name**：图案分组及其名称。
* **colour_group_code, colour_group_name**：颜色分组及其名称。
* **perceived_colour_value_id, perceived_colour_value_name, perceived_colour_master_id, perceived_colour_master_name**：附加的颜色信息。
* **department_no, department_name**：每个部门的唯一标识符及其名称。
* **index_code, index_name**：每个索引的唯一标识符及其名称。
* **index_group_no, index_group_name**：索引分组及其名称。
* **section_no, section_name**：每个分区的唯一标识符及其名称。
* **garment_group_no, garment_group_name**：服装分组的唯一标识符及其名称。
* **detail_desc**：商品详细描述。

In [6]:
articles.head()

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,108775015,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,10,White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
2,108775051,108775,Strap top (1),253,Vest top,Garment Upper body,1010017,Stripe,11,Off White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
3,110065001,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,9,Black,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
4,110065002,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,10,White,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."

In [10]:
# 删除无用的数据
articles=articles[[column for column in articles.columns if column.split('_')[-1]!='name']]
articles.drop(columns=['detail_desc'],inplace=True)

In [11]:
articles.head()

,article_id,product_code,product_type_no,graphical_appearance_no,colour_group_code,perceived_colour_value_id,perceived_colour_master_id,department_no,index_code,index_group_no,section_no,garment_group_no
0,108775015,108775,253,1010016,9,4,5,1676,A,1,16,1002
1,108775044,108775,253,1010016,10,3,9,1676,A,1,16,1002
2,108775051,108775,253,1010017,11,1,9,1676,A,1,16,1002
3,110065001,110065,306,1010016,9,4,5,1339,B,1,61,1017
4,110065002,110065,306,1010016,10,3,9,1339,B,1,61,1017

In [13]:
# 观察独特的数值
for col in articles.columns:
    if 'no'in col or 'code' in col:
        un_n=articles[col].nunique()
        print(f'n of unique {col}: {un_n}')

n of unique product_code: 47224
n of unique product_type_no: 132
n of unique graphical_appearance_no: 30
n of unique colour_group_code: 50
n of unique department_no: 299
n of unique index_code: 10
n of unique index_group_no: 5
n of unique section_no: 57
n of unique garment_group_no: 21

In [16]:
articles.to_parquet('../data/articles.parquet')

# customer

In [19]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1371980 entries, 0 to 1371979
Data columns (total 7 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   customer_id             1371980 non-null  object
 1   FN                      476930 non-null   float64
 2   Active                  464404 non-null   float64
 3   club_member_status      1365918 non-null  object
 4   fashion_news_frequency  1355969 non-null  object
 5   age                     1356119 non-null  float64
 6   postal_code             1371980 non-null  object
dtypes: float64(3), object(4)
memory usage: 73.3+ MB

* **customer_id**：每位客户的唯一标识符
* **FN**：1 或缺失（可能表示客户是否填写了某些信息）
* **Active**：1 或缺失（可能表示客户是否活跃）
* **club_member_status**：会员状态
* **fashion_news_frequency**：H&M 向客户发送时尚资讯的频率
* **age**：当前年龄
* **postal_code**：客户的邮政编码

In [21]:
customers.head()

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,NaN,NaN,ACTIVE,NONE,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,NaN,NaN,ACTIVE,NONE,25.0,2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,NaN,NaN,ACTIVE,NONE,24.0,64f17e6a330a85798e4998f62d0930d14db8db1c054af6...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,NaN,NaN,ACTIVE,NONE,54.0,5d36574f52495e81f019b680c843c443bd343d5ca5b1c2...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,1.0,ACTIVE,Regularly,52.0,25fa5ddee9aac01b35208d01736e57942317d756b32ddd...

In [26]:
customers['Active'].value_counts()

Active
1.0    464404
Name: count, dtype: int64

In [33]:
customers['FN'].value_counts()

FN
1.0    476930
Name: count, dtype: int64

In [42]:
customers['fashion_news_frequency'].value_counts()

fashion_news_frequency
NONE         877711
Regularly    477416
Monthly         842
Name: count, dtype: int64

In [44]:
customers['fashion_news_frequency'].value_counts()

fashion_news_frequency
NONE         877711
Regularly    477416
Monthly         842
Name: count, dtype: int64

In [54]:
# 填充缺失值
customers['Active'].fillna(0,inplace=True)
customers['FN'].fillna(0,inplace=True)
customers['FN']=customers['FN'].astype('uint8')
customers['Active']=customers['Active'].astype('uint8')

customers['age'].fillna(customers['age'].mean(),inplace=True)
customers['club_member_status'].fillna(customers['club_member_status'].mode()[0],inplace=True)
customers['fashion_news_frequency'].fillna(customers['fashion_news_frequency'].mode()[0],inplace=True)

C:\Users\ROG\AppData\Local\Temp\ipykernel_564\3102396037.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customers['Active'].fillna(0,inplace=True)
C:\Users\ROG\AppData\Local\Temp\ipykernel_564\3102396037.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customers['FN'].fillna(0,inplace=True)
C:\Users\ROG\AppData\Local\Temp\ipykernel_564\3102396037.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customers['age'].fillna(customers['age'].mean(),inplace=True)
C:\Users\ROG\AppData\Local\Temp\ipykernel_564\3102396037.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customers['club_member_status'].fillna(customers['club_member_status'].mode()[0],inplace=True)
C:\Users\ROG\AppData\Local\Temp\ipykernel_564\3102396037.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customers['fashion_news_frequency'].fillna(customers['fashion_news_frequency'].mode()[0],inplace=True)

In [55]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1371980 entries, 0 to 1371979
Data columns (total 7 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   customer_id             1371980 non-null  object
 1   FN                      1371980 non-null  uint8
 2   Active                  1371980 non-null  uint8
 3   club_member_status      1371980 non-null  object
 4   fashion_news_frequency  1371980 non-null  object
 5   age                     1371980 non-null  float64
 6   postal_code             1371980 non-null  object
dtypes: float64(1), object(4), uint8(2)
memory usage: 55.0+ MB

In [56]:
customers.head()

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,0,0,ACTIVE,NONE,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,0,0,ACTIVE,NONE,25.0,2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0,0,ACTIVE,NONE,24.0,64f17e6a330a85798e4998f62d0930d14db8db1c054af6...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,0,0,ACTIVE,NONE,54.0,5d36574f52495e81f019b680c843c443bd343d5ca5b1c2...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1,1,ACTIVE,Regularly,52.0,25fa5ddee9aac01b35208d01736e57942317d756b32ddd...

In [ ]:
customers['age'].hist()

In [57]:
bins=[0,40,60,float('inf')]
labels=[0,1,2]
customers['age']=pd.cut(customers['age'],bins=bins,labels=labels)
customers.head()

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,0,0,ACTIVE,NONE,1,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,0,0,ACTIVE,NONE,0,2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0,0,ACTIVE,NONE,0,64f17e6a330a85798e4998f62d0930d14db8db1c054af6...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,0,0,ACTIVE,NONE,1,5d36574f52495e81f019b680c843c443bd343d5ca5b1c2...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1,1,ACTIVE,Regularly,1,25fa5ddee9aac01b35208d01736e57942317d756b32ddd...

In [58]:
customers=pd.get_dummies(customers,columns=['fashion_news_frequency','club_member_status','age'])

In [62]:
customers.head()

,customer_id,FN,Active,postal_code,fashion_news_frequency_Monthly,fashion_news_frequency_NONE,fashion_news_frequency_Regularly,club_member_status_ACTIVE,club_member_status_LEFT CLUB,club_member_status_PRE-CREATE,age_0,age_1,age_2
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,0,0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...,False,True,False,True,False,False,False,True,False
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,0,0,2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93...,False,True,False,True,False,False,True,False,False
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0,0,64f17e6a330a85798e4998f62d0930d14db8db1c054af6...,False,True,False,True,False,False,True,False,False
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,0,0,5d36574f52495e81f019b680c843c443bd343d5ca5b1c2...,False,True,False,True,False,False,False,True,False
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1,1,25fa5ddee9aac01b35208d01736e57942317d756b32ddd...,False,False,True,True,False,False,False,True,False

In [64]:
customers.drop(['postal_code'],inplace=True,axis=1)

In [65]:
customers.to_parquet('../data/customers.parquet')

# Transactions

In [67]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31788324 entries, 0 to 31788323
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   t_dat             object
 1   customer_id       object
 2   article_id        int64
 3   price             float64
 4   sales_channel_id  int64
dtypes: float64(1), int64(2), object(2)
memory usage: 1.2+ GB

交易数据说明：

* **t_dat**：每笔交易的日期（原文可能有误，通常是日期，而不是唯一标识符）
* **customer_id**：每位客户的唯一标识符（对应 customers 表）
* **article_id**：每件商品的唯一标识符（对应 articles 表）
* **price**：购买价格
* **sales_channel_id**：销售渠道，1 或 2

In [70]:
transactions['sales_channel_id']=transactions['sales_channel_id'].astype('uint8')

In [71]:
transactions['t_dat']=pd.to_datetime(transactions['t_dat'])
transactions['time']=transactions['t_dat'].apply(lambda x: x.timestamp())

In [73]:
transactions.drop(['t_dat'],inplace=True,axis=1)

In [74]:
transactions.head()

,customer_id,article_id,price,sales_channel_id,time
0,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,663713001,0.050831,2,1.537402e+09
1,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,541518023,0.030492,2,1.537402e+09
2,00007d2de826758b65a93dd24ce629ed66842531df6699...,505221004,0.015237,2,1.537402e+09
3,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687003,0.016932,2,1.537402e+09
4,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687004,0.016932,2,1.537402e+09

In [75]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31788324 entries, 0 to 31788323
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   customer_id       object
 1   article_id        int64
 2   price             float64
 3   sales_channel_id  uint8
 4   time              float64
dtypes: float64(2), int64(1), object(1), uint8(1)
memory usage: 1000.4+ MB

In [76]:
transactions.to_parquet('../data/transactions.parquet')